### PR TITLE
Delete deprecated instances

### PR DESCRIPTION
**Pull request by tiekoetter**

### CODE REVIEW

**Comment by unixfox** [comment]
Mmh about that, I would prefer that we at least contact the maintainer instead of removing them.

**Comment by tiekoetter** [comment]
Agree. I contacted the maintainer of searx.lavatech.top for example. She said it is deprecated. See: https://lavate.ch/

**Comment by unixfox** [comment]
Okay thanks. For all the deprecated instances, you can straight remove them from the code without a PR.

**Comment by tiekoetter** [comment]
Yeah I know but I don't want to accidentally mess something up.

I will try to contact all the other instance maintainers. How much time should we give them if they don't respond?

**Pull request merged**
